site_name: vec2pg
site_url: https://supabase-community.github.io/vec2pg
site_description: A CLI for migrating vector data to Supabase

repo_name: supabase-community/vec2pg
repo_url: https://github.com/supabase-community/vec2pg

nav:
    - Welcome: 'index.md'
    - Installation: 'installation.md'
    - Vendors:
      - Pinecone: 'pinecone.md'
      - Qdrant: 'qdrant.md'
    - Contributing: 'contributing.md'

theme:
    name: 'material'
    favicon: 'assets/favicon.ico'
    logo: 'assets/favicon.ico'
    homepage: https://supabase-community.github.io/vec2pg
    features:
      - navigation.expand
    palette:
        primary: black
        accent: light green

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
        guess_lang: false
        use_pygments: true
        pygments_style: default
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
    - pymdownx.tasklist
    - admonition
